### ISSUE TITLE
Advertising in android app crash

### ISSUE THREAD

**Issue by hern12** [vitorpamplona/react-native-ble-advertiser#10]
When I use Advertise function in android app is stop working on android but on iPhone 11 and 10 work perfect thanks

**Comment by vitorpamplona** [comment]
hum... I just cleared my env to test this and it seems to be working fine. 

Can you post the error message? 

It could be the: 

```js
      eventEmitter.addListener('onDeviceFound', (event) => {
       console.log('onDeviceFound', event);
```

I realized that console.log at every second could be quite heavy for some phones.

**Comment by aongwachi1** [comment]
You suggest to remove console.log in event listener, right?
@vitorpamplona

**Comment by hern12** [comment]
It seems native code error. I forget to capture the error image. I will post the image later.
Can I check Bluetooth version before init Adv. Thank you in advance
