### ISSUE TITLE
Unable to resolve module `moment.js` from `app/Entry.js`: moment.js could not be found within the project

### ISSUE THREAD

**Issue by venkatmanavarthi** [vitorpamplona/react-native-ble-advertiser#11]
Unable to resolve module `moment.js` from `app/Entry.js`: moment.js could not be found within the project.
![Screenshot 2020-06-23 at 2 38 12 PM](https://user-images.githubusercontent.com/41376932/85385042-748ade80-b55f-11ea-877d-2ed9085bdbb8.png)

**Comment by vitorpamplona** [comment]
Did you run npm install on the example folder? Moment is declared in the package.json file, so it should install when you run it.

**Comment by venkatmanavarthi** [comment]
Yes

**Comment by vitorpamplona** [comment]
See if you can find a example/node_modules/moment/moment.js file

If it is not there, your react-native install is faulty. If it is, your Metro VM is the problem.
