### ISSUE TITLE
Is it possible to use to connect to a bluetooth module ble?

### ISSUE THREAD

**Issue by vagnerwentz** [vitorpamplona/react-native-ble-advertiser#17]
Hello! I have a doubt I would like to know if this library can do the same about `react-native-ble-plx` or `react-native-ble-manager`. If it is possible to read and write, send a command and receive the data for example, because I am using the `react-native-ble-plx` but it is not working.

**Comment by vitorpamplona** [comment]
No, this library is just for advertising and scanning of devices. But you are free to implement the added modules to make the BLE server and client.

**Comment by vagnerwentz** [comment]
> No, this library is just for advertising and scanning of devices. But you are free to implement the added modules to make the BLE server and client.

Thanks friend
