### ISSUE TITLE
Advertising additional data

### ISSUE THREAD

**Issue by ayoubphy** [vitorpamplona/react-native-ble-advertiser#2]
Hello, I want to advertise additional data, like a token or another UUID, how can I do that ?
Also, for iOS advertising in the background I have found a work around which is to connect to the device before reading any data from it, is there a way to connect on scan ?

**Comment by vitorpamplona** [comment]
Hi there, 

BLE is very limiting on the number of bytes you can advertise. I suggest either using a fully-fledged Bluetooth library that allows you to connect with each other and exchange additional data or use this one while mapping the information you want to expose the service UUID form (16 bytes). 

Best,
