### ISSUE TITLE
Manufacturer specific data

### ISSUE THREAD

**Issue by mathiasvdb1998** [vitorpamplona/react-native-ble-advertiser#24]
For my master thesis I'm trying to implement a BLE advertiser to send BLE packets for an indoor positioning system.
I received some info about the packet format and the manufacturer specific data from the manufacturer of the indoor positioning system.

![BLE_Advertising_data](https://user-images.githubusercontent.com/49117530/114849000-9bace800-9ddf-11eb-8477-0381a829790b.png)
![BLE_Manufacturer_data](https://user-images.githubusercontent.com/49117530/114849007-9cde1500-9ddf-11eb-9ab6-5bf0ebce1418.png)

I just don't know if I need to add the company ID in the manufacturer data when I start broadcasting.

I also get an error when I try to set the company ID.

<img src="https://user-images.githubusercontent.com/49117530/114849206-d31b9480-9ddf-11eb-81f3-4f34cb2ea0c8.jpg" height="400">

Can someone help me please?

**Comment by vitorpamplona** [comment]
Hi Mathias, 

You don't need to, but it's a way to keep the Advertising going on in the background in some android phones.

**Comment by vitorpamplona** [comment]
Also, please check the example project for the setCompanyId.

**Comment by mathiasvdb1998** [comment]
Hi Vitor

Thanks for the quick response.
I had a look at the example before and in my mind I set the CompanyID the right way.

Here's my code:
![code](https://user-images.githubusercontent.com/49117530/114873080-3e269480-9dfb-11eb-9111-319fe7497700.png)

Maybe you can find what i'm doing wrong?

**Comment by vitorpamplona** [comment]
Aren't you redefining BLEAdvertiser?

**Comment by mathiasvdb1998** [comment]
That was pretty stupid of me.
I changed the name of my component, but I still get the same error when I call `BLEAdvertiser.setCompanyId(0x00c7)`.

**Comment by lnogueir** [comment]
@mathiasvdb1998 were you able to resolve the issue at all? I have the same problem.
