### ISSUE TITLE
Get MAC Address

### ISSUE THREAD

**Issue by JuliaGmP** [vitorpamplona/react-native-ble-advertiser#3]
Hello!
Is there a way to get the MAC address after starting to broadcast? The mac address you are broadcasting with.
Thank you!

**Comment by vitorpamplona** [comment]
Hi Julia, 

I am not sure if you can rely on the Mac Address, since many phones rotate the addresses in ways that are hard to control: https://www.mist.com/documentation/ble-mac-randomization/

But I am happy to accept a pull request if you find a way around.
