### ISSUE TITLE
Cant see manufacturer data from device broadcasting. 

### ISSUE THREAD

**Issue by tomhobsonxd** [vitorpamplona/react-native-ble-advertiser#37]
Hi,
Followed the example and I can see my iPad broadcasting Eddystone (using UUID FEAA) or a general one with any UUID V1/V4. However, I cannot see any of the data that I pass in through the [manufacturer data] object.

Any ideas?

**Comment by vitorpamplona** [comment]
Unfortunately, Apple doesn't allow unregistered changes in the Manufacturer's data. :(
