### ISSUE TITLE
IOS Not advertising

### ISSUE THREAD

**Issue by gezperez** [vitorpamplona/react-native-ble-advertiser#6]
Hello, im having an issue where i cant advertise my IOS devices, y can scan from IOS, and i can advertise and scan from android, im using the exact same example from de repo. 

Any advise would be much appreciated.

Thanks!

**Comment by fhllnd** [comment]
@gezperez would you be able to share your bleadvertiser setup to go from iOS to Android if possible? I'm currently using the apple company id and [1, 0] manufacturer data. Thanks
