### ISSUE TITLE
use BLEAdvertiser.scan error got 2 parameter but expect 3 

### ISSUE THREAD

**Issue by hern12** [vitorpamplona/react-native-ble-advertiser#9]
I have followed the example but when I run in IOS I got error like this
![IMG_4464](https://user-images.githubusercontent.com/13413078/84563425-b8266100-ad85-11ea-87e0-e1526ebcb2e2.PNG)
I don't know how to fix this.

**Comment by mehr30na** [comment]
The same error for me. Any solutions?

**Comment by vitorpamplona** [comment]
Hi @hern12 and @mehr30na 

Apologies for the delay. I just released a new version (0.0.16) that should fix this issue. 

Thanks for letting me know!
